#!/bin/bash
 
now=`date +'%Y-%m-%d %H:%M:%S'`
start_time=$(date --date="$now" +%s);
 
if [ ! -d "out" ];then
    mkdir out
    sleep 2
    echo "新建out文件夹..."
else
    rm -rf out
    sleep 3
    echo "删除out文件夹完成..."
    sleep 1
    echo "正在重新创建out文件夹..."
    mkdir out
    echo "创建完成..."
fi

sleep 2
echo "开始编译..."

N_CORE=$1 #核心数量 ./build 4
PATH1=/usr/bin
GCC=$PATH1/arm-linux-gnueabi-gcc-4.9
LD=$PATH1/arm-linux-gnueabi-ld
DECONFIG=$2 #deconfig配置 ./build 4 msm8916-deconfig

echo ======================================================================================================
CROSS_COMPILE=$PATH1/arm-linux-gnueabi-
make O=out ARCH=arm CC=${GCC} LD=${LDD} CROSS_COMPILE=${CROSS_COMPILE} ${DECONFIG}
make O=out ARCH=arm CC=${GCC} CROSS_COMPILE=${CROSS_COMPILE} -j$N_CORE 2>&1 | tee kernel.log

if [ ! -f "out/arch/arm/boot/zImage" ];then
    echo "编译失败,请重新编译..."
else
    mv out/arch/arm/boot/zImage AnyKernel3/
    echo "移动zImage到Anykernel3..."
    cd AnyKernel3
    zip -r Y51A_kernel.zip *
    cd ..
fi
echo ======================================================================================================


now=`date +'%Y-%m-%d %H:%M:%S'`
end_time=$(date --date="$now" +%s);
echo "使用了: "$((end_time-start_time))"s"
